In [50]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [51]:
import pandas as pd

In [52]:
df = pd.DataFrame(people)

In [53]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [54]:
df["email"]    # Acessando a coluna email

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [55]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [ ]:
# Define o índice para a coluna email e modifica o DataFrame original
df.set_index("email", inplace=True)
# o inplace=True é necessário para modificar o DataFrame original, caso contrário,
# ele retornaria um novo DataFrame com o índice definido, mas não modificaria o DataFrame original.

In [57]:
df

                         first     last
email
CoreyMSchafer@gmail.com  Corey  Schafer
JaneDoe@email.com         Jane      Doe
JohnDoe@email.com         John      Doe

In [58]:
df.loc["CoreyMSchafer@gmail.com", "last"]

'Schafer'

In [59]:
df.iloc[1]

first    Jane
last      Doe
Name: JaneDoe@email.com, dtype: str

In [60]:
df.loc["JaneDoe@email.com"]

first    Jane
last      Doe
Name: JaneDoe@email.com, dtype: str

In [61]:
df.reset_index(inplace=True)    # Reseta o índice para o padrão numérico e modifica o DataFrame original
df

                     email  first     last
0  CoreyMSchafer@gmail.com  Corey  Schafer
1        JaneDoe@email.com   Jane      Doe
2        JohnDoe@email.com   John      Doe