In [124]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [125]:
import pandas as pd

In [126]:
df = pd.DataFrame(people)

In [127]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [128]:
df.columns

Index(['first', 'last', 'email'], dtype='str')

In [129]:
df.columns = ['first_name','last_name', 'email']

In [130]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [131]:
df.columns = [x.upper() for x in df.columns]
df

  FIRST_NAME LAST_NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [132]:
df.columns = df.columns.str.replace('_',' ')
df

  FIRST NAME LAST NAME                    EMAIL
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [133]:
df.columns = df.columns.str.replace(' ','_')
df.columns = [x.lower() for x in df.columns]

In [134]:
df

  first_name last_name                    email
0      Corey   Schafer  CoreyMSchafer@gmail.com
1       Jane       Doe        JaneDoe@email.com
2       John       Doe        JohnDoe@email.com

In [135]:
df.rename(columns={'first_name':'first', 'last_name': 'last'}, inplace = True)
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [136]:
df.loc[2] = ['John','Smith','JhonSmith@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John    Smith      JhonSmith@email.com

In [137]:
df.loc[2, ['last','email']]

last                   Smith
email    JhonSmith@email.com
Name: 2, dtype: str

In [138]:
df.loc[2, ['last','email']] = ['Matheus', 'Matheus@email.com']
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [139]:
df.loc[2,'last'] = 'Carlos'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John   Carlos        Matheus@email.com

In [140]:

# Usando o método at para atualizar um valor específico
# O método at é mais rápido do que loc para acessar um único valor, pois é otimizado para esse tipo de operação.
df.at[2,'last'] = 'Matheus'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [141]:
filtro = (df['email'] == 'JaneDoe@email.com')
df[filtro]['last'] = 'Smith'
df

# Essa operação não funciona porque o filtro retorna uma cópia do DataFrame, e não uma visão.
# Portanto, quando tentamos atualizar a coluna 'last' usando o filtro, estamos atualizando a cópia, e não o DataFrame original.
# Para atualizar o DataFrame original, precisamos usar loc ou at para acessar as linhas correspondentes ao filtro e atualizar a coluna 'last' diretamente no DataFrame original.

/tmp/ipykernel_70439/542588989.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df[filtro]['last'] = 'Smith'

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [142]:
filtro = (df['email'] == 'JaneDoe@email.com')
df.loc[filtro, 'last'] = 'Smith'
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane    Smith        JaneDoe@email.com
2   John  Matheus        Matheus@email.com

In [143]:
df['email']

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          Matheus@email.com
Name: email, dtype: str

In [144]:
df['email'].str.upper()

0    COREYMSCHAFER@GMAIL.COM
1          JANEDOE@EMAIL.COM
2          MATHEUS@EMAIL.COM
Name: email, dtype: str

In [145]:
df['email'] = df['email'].str.upper()
df

   first     last                    email
0  Corey  Schafer  COREYMSCHAFER@GMAIL.COM
1   Jane    Smith        JANEDOE@EMAIL.COM
2   John  Matheus        MATHEUS@EMAIL.COM