In [25]:
person = {
    "first": "Corey",
    "last": "Schafer",
    "email": "CoreyMSchafer@gmail.com"
}

In [26]:
people = {
    "first": ["Corey"],
    "last": ["Schafer"],
    "email": ["CoreyMSchafer@gmail.com"]
}

In [27]:
# As chaves são as colunas e os valores são as linhas, ou seja, os dados de cada pessoa.

people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [28]:
people["email"] # Acessa a coluna "email" do dicionário 'people' e retorna os valores associados a essa chave, que são os endereços de email das pessoas.

['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']

In [29]:
import pandas as pd

In [30]:
df = pd.DataFrame(people) # Cria um DataFrame a partir do dicionário 'people'.
# O DataFrame é uma estrutura de dados bidimensional, semelhante a uma tabela,
# que pode conter diferentes tipos de dados (como números, strings, etc.)
# e é amplamente utilizado para análise de dados em Python.

In [31]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [32]:
df["email"] # Acessa a coluna "email" do DataFrame 'df' e retorna os valores associados a essa coluna, que são os endereços de email das pessoas.
# É o que se chama de Series, que é uma estrutura de dados unidimensional do Pandas, semelhante a uma coluna em uma tabela, que pode conter diferentes tipos de dados e é indexada.

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [33]:
df.email # Acessa a coluna "email" do DataFrame 'df' usando a notação de ponto, que é uma forma alternativa de acessar colunas em um DataFrame do Pandas.
# No entanto, essa notação só funciona se o nome da coluna for um identificador válido (sem espaços, caracteres especiais, etc.)
# e não for o mesmo que um método ou atributo do DataFrame.

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
2          JohnDoe@email.com
Name: email, dtype: str

In [34]:
type(df["email"]) # Verifica o tipo do objeto retornado ao acessar a coluna "email" do DataFrame 'df', que é uma Series do Pandas.

pandas.Series

In [35]:
df[["last", "email"]] # Acessa as colunas "last" e "email" do DataFrame 'df' e retorna um novo DataFrame contendo apenas essas colunas.

      last                    email
0  Schafer  CoreyMSchafer@gmail.com
1      Doe        JaneDoe@email.com
2      Doe        JohnDoe@email.com

In [36]:
df.columns # Retorna um objeto Index contendo os rótulos das colunas do DataFrame 'df', que são "first", "last" e "email".

Index(['first', 'last', 'email'], dtype='str')

Funções iloc e loc

In [37]:
df.iloc[0] # Acessa a primeira linha do DataFrame 'df' usando o método iloc, que é baseado em índices inteiros.
# Retorna uma Series contendo os valores da primeira linha.

first                      Corey
last                     Schafer
email    CoreyMSchafer@gmail.com
Name: 0, dtype: str

In [38]:
df.iloc[[0, 1]] # Acessa as primeiras duas linhas do DataFrame 'df' usando o método iloc e retorna um novo DataFrame contendo essas linhas.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [39]:
df.iloc[[0, 1], 2] # Acessa as primeiras duas linhas e a terceira coluna (índice 2) do DataFrame 'df'
# usando o método iloc e retorna os valores correspondentes, que são os endereços de email das duas primeiras pessoas.

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str

In [40]:
df.iloc[[0, 1], [2, 0]] # Acessa as primeiras duas linhas e as colunas de índice 2 e 0 do DataFrame 'df'
# usando o método iloc e retorna os valores correspondentes,
# que são os endereços de email e os primeiros nomes das duas primeiras pessoas.

# É possível mudar a ordem das colunas e linhas usando o método iloc, basta especificar os índices na ordem desejada.

                     email  first
0  CoreyMSchafer@gmail.com  Corey
1        JaneDoe@email.com   Jane

In [41]:
df.loc[[0,1], ["email", "first"]] # Acessa as primeiras duas linhas e as colunas "email" e "first" do DataFrame 'df' usando o método loc, que é baseado em rótulos.
# Retorna os valores correspondentes, que são os endereços de email e os primeiros

                     email  first
0  CoreyMSchafer@gmail.com  Corey
1        JaneDoe@email.com   Jane