In [1]:
people = {
    "first": ["Corey", 'Jane', 'John'],
    "last": ["Schafer", 'Doe', 'Doe'],
    "email": ["CoreyMSchafer@gmail.com", 'JaneDoe@email.com', 'JohnDoe@email.com']
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(people)

In [4]:
df

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com
2   John      Doe        JohnDoe@email.com

In [8]:
filtro = (df['last'] == 'Doe' ) # Retorna una Serie de valores booleanos indicando se o valor na coluna 'last' é igual a 'Doe' para cada linha do DataFrame.

In [9]:
df[filtro] # Retorna um DataFrame contendo apenas as linhas onde a condição do filtro é verdadeira, ou seja, onde a coluna 'last' é igual a 'Doe'.

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [ ]:
df[df['last'] == 'Doe'] # Retorna um DataFrame contendo apenas as linhas onde a coluna 'last' é igual a 'Doe', sem a necessidade de criar uma variável intermediária para o filtro.

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [ ]:
df.loc[filtro] # Usando a indexação .loc para obter o mesmo resultado do filtro, retornando um DataFrame contendo apenas as linhas onde a coluna 'last' é igual a 'Doe'.

  first last              email
1  Jane  Doe  JaneDoe@email.com
2  John  Doe  JohnDoe@email.com

In [12]:
df.loc[filtro, 'email'] # Retorna apenas a coluna 'email' das linhas onde a coluna 'last' é igual a 'Doe',
# usando a indexação .loc para filtrar as linhas e selecionar a coluna específica.

1    JaneDoe@email.com
2    JohnDoe@email.com
Name: email, dtype: str

In [ ]:
filtro2 = (df['last'] == 'Doe') & (df['first'] == 'John') # Combina dois filtros usando o operador lógico AND (&) para criar
# um filtro que retorna True apenas para as linhas onde a coluna 'last' é igual a 'Doe' e a coluna 'first' é igual a 'John'.

# & = AND
# | = OR
# ~ = NOT

In [21]:
df[filtro2]

  first last              email
2  John  Doe  JohnDoe@email.com

In [ ]:
df.loc[filtro2,'email'] # Retorna apenas a coluna 'email' das linhas onde ambas as condições do filtro são verdadeiras.

2    JohnDoe@email.com
Name: email, dtype: str

In [23]:
df.loc[~filtro2] # Retorna a coluna 'email' das linhas onde a condição do filtro2 é falsa,
# ou seja, onde a coluna 'last' não é igual a 'Doe' ou a coluna 'first' não é igual a 'John'.

   first     last                    email
0  Corey  Schafer  CoreyMSchafer@gmail.com
1   Jane      Doe        JaneDoe@email.com

In [24]:
df.loc[~filtro2, 'email'] # Retorna apenas a coluna 'email' das linhas onde a condição do filtro2 é falsa, usando a indexação
# .loc para filtrar as linhas e selecionar a coluna específica.

0    CoreyMSchafer@gmail.com
1          JaneDoe@email.com
Name: email, dtype: str